import numpy as np
import pandas as pd

pd.set_option('display.max_columns', 100)
pd.set_option('display.width', 2000)
pd.set_option('display.max_rows', 2000)
# df1 =  pd.read_csv('Data_for_pandas/Fishing.csv')
# print(type(df1))
# print(df1)
# df1 = pd.read_excel('Data_for_pandas/4 wave p&db (1).xlsx', sheet_name="Performance2", header = 1)
np_array = np.load('Data_for_pandas/arr_pandas.npy', allow_pickle=True)
df1 = pd.DataFrame(np_array)
print(df1)
print(type(df1))
#["name","dist","climb","time","timef","type"]
#1. Стандартная индексация df1[5:-1]
#2. df1.loc[5:-1]
#3. df1.iloc[5:-1]
#A - Датафрейм имеет цифровые цифровые названия колонок и строк
#B - Датафрейм имеет цифровые строковые названия колонок и строк
#A - 1
print('=============== A-1 ===============')
print(df1[5:8])
print(type(df1))
# print(df1[5])
# print(type(df1[5]))
# print(df1[5:8][5])
# print(type(df1[5:8][5]))
print('=============== A-2 ===============')
print(df1.loc[5:8])
print(type(df1.loc[5:8]))
print(df1.loc[5])
print(type(df1.loc[5]))
print(df1.loc[5:8, 5])
print(type(df1.loc[5:8, 5]))
print(df1.loc[5:8, 0:2])
print(type(df1.loc[5:8, 0:2]))
print('=============== A-3 ===============')
print(df1.iloc[5:8])
print(type(df1.iloc[5:8]))
print(df1.iloc[5])
print(type(df1.iloc[5]))
print(df1.iloc[5:8, 5])
print(type(df1.iloc[5:8, 5]))
print(df1.iloc[5:8, 0:2])
print(type(df1.iloc[5:8, 0:2]))
b_s1 = (df1[3]> 0.5) & (df1[4] > 0.5)
print(b_s1)
print(type(b_s1))
b_df1 = df1.loc[:, 3:4] > .5
print(b_df1)
print(type(b_df1))
print('=============== A-1.1 булевы выборки ===============')
print(df1[b_df1])
print(type(df1[b_df1]))
# print(df1[2:5][b_s1])
# print(type(df1[2:5][b_s1]))
# print(df1[2:5][b_df1])
# print(type(df1[2:5][b_df1]))
print('=============== A-2.1 булевы выборки ===============')
# print(df1.loc[b_df1])
# print(type(df1.loc[b_df1]))
# print(df1.loc[2:5][b_s1])
# print(type(df1.loc[2:5][b_s1]))
# print('=============== A-3.1 булевы выборки ===============')
# # print(df1.iloc[b_df1])
# # print(type(df1.iloc[b_df1]))
# print(df1.iloc[2:5][b_s1])
# print(type(df1.iloc[2:5][b_s1]))
print('=============== B-1 именованные колонки и строки ===============')
#["name","dist","climb","time","timef","type"]
df2 = df1[:3]
print(df2)
print(type(df2))
df2.columns = ["name","dist","climb","time","timef","type"]
print(df2)
print(type(df2))
df2.index = ["third", "second", "first"]
print(df2)
print(type(df2))
print(df2[0:2])
print(type(df2[0:2]))
# print(df2[5])
# print(type(df2[5]))
print(df2["name"])
print(type(df2["name"]))
print(df2[0:2][["name","dist"]])
print(type(df2[0:2][["name","dist"]]))
# print(df2[:, "name":"climb"])
# print(type(df2[:, "name":"climb"]))
print('=============== B-2 .loc именованные колонки и строки ===============')
# print(df2.loc[0:2])
# print(type(df2.loc[0:2]))
print(df2.loc["third": "second" ])
print(type(df2.loc["third": "second"]))
# print(df2.loc[:, "name":"climb"])
# print(type(df2.loc[:, "name":"climb"]))
print('=============== B-2 .iloc именованные колонки и строки ===============')
# print(df2.iloc[0:2])
# print(type(df2.iloc[0:2]))
# print(df2.iloc["third": "second" ])
# print(type(df2.iloc["third": "second"]))
# print(df2.iloc[:, "name":"climb"])
# print(type(df2.iloc[:, "name":"climb"]))
print('=============== B-1.1 булевы выборки ===============')
b_df2 = df2.loc[:, "time":"timef"] > .4
b_s2 = (df2["time"]> 0.4) & (df2["timef"] > 0.5)
print(b_df2)
print(type(b_df2))
print(df2[b_df2])
print(type(df2[b_df2]))
print(b_s2)
print(type(b_s2))
print(df2[b_s2])
print(type(df2[b_s2]))
print('=============== B-2.1 .loc булевы выборки ===============')
b_df2 = df2.iloc[:, 3:5] > .4
print(b_df2)
print(type(b_df2))
# print(df2.loc[b_df2])
# print(type(df2.loc[b_df2]))
print(df2.loc[b_s2])
print(type(df2.loc[b_s2]))
print('=============== B-3.1 .iloc булевы выборки ===============')
# print(df2.iloc[b_df2])
# print(type(df2.iloc[b_df2]))
# print(df2.iloc[b_df1])
# print(type(df2.iloc[b_df1]))
# print(df2.iloc[b_s2])
# print(type(df2.iloc[b_s2]))
b_s1 = (df2.iloc[:,3]> 0.4) & (df2.iloc[:,4] > 0.5)
print(b_s1)
print(type(b_s1))
# print(df2.iloc[b_s1])
# print(type(df2.iloc[b_s1]))
# print("----")