import asyncio
import asyncpg
import pandas as pd
from decouple import config

async def create_psql(text:str):
    conn = await asyncpg.connect(
        user=config("user_pg"),
        password=config("password_pg"),
        database=config("database_pg"),
        host=config("host_pg"),
        port=config("port_pg")
    )

    rows = await conn.fetch(text)
    # dt_rows = pd.DataFrame(rows)
    # for row in rows:
    #     print(row)
    await conn.close()
    return rows

async def create_menu():
    create_text = """
    CREATE TABLE public.menu (
	id int8 NOT NULL,
	pizzeria_id int8 NOT NULL,
	pizza_name varchar NOT NULL,
	price numeric DEFAULT 1 NOT NULL,
	CONSTRAINT menu_pkey PRIMARY KEY (id),
	CONSTRAINT fk_menu_pizzeria_id FOREIGN KEY (pizzeria_id) REFERENCES public.pizzeria(id)
    );
    """
    return await create_psql(create_text)

async def create_tbl(table, columns, scheme_name):
    #columns {column_name: {type: "int8", specs: {}}}
    #{"id":{"type": "int", "autoinc": True, "nn": True, "fk": "mothers"}}
    #await create_psql(f"DROP TABLE IF EXISTS {table};")
    com_specs = {"type": {"int": "int8", "str": "varchar", "date": "date", "datetime": "datetime"},
                 "autoinc": "GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE)",
                 "nn": "NOT NULL",
                 "pk": "CONSTRAINT",
                 "fk": "CONSTRAINT"
                }
    column_strs = [] # ",".join(["1", "2", "3"]) -> "1,2,3"
    fk_strs = []
    for column, params in columns.items():
        column_str = []
        column_str += [f"{column}"]
        for spec in com_specs:
            if spec in columns[column]:
                if spec == "type":
                    column_str += [f"{com_specs[spec][columns[column]["type"]]}"]
                if spec == "autoinc" and columns[column]["autoinc"]:
                    column_str += [f"{com_specs[spec]}"]
                if spec == "nn" and columns[column]["nn"]:
                    column_str += [f"{com_specs[spec]}"]
                if spec == "fk" and isinstance(columns[column]["fk"], str): #CONSTRAINT fk_menu_pizzeria_id FOREIGN KEY (pizzeria_id) REFERENCES scheme_name.pizzeria(id)
                    fk_strs += [f"{com_specs[spec]} fk_{table}_{columns[column]["fk"]}_id  FOREIGN KEY ({column}) REFERENCES {scheme_name}.{columns[column]["fk"]}(id)"]
                if spec == "pk" and columns[column]["pk"]: #CONSTRAINT menu_pkey PRIMARY KEY (id)
                    fk_strs += [f"{com_specs[spec]} {table}_pkey  PRIMARY KEY (id)"]
        column_strs += [" ".join(column_str)] #.append(" ".join(column_str))
    column_strs += fk_strs
    column_strs = ",\n".join(column_strs)
    create_text = f"""
    CREATE TABLE IF NOT EXISTS {scheme_name}.{table} (
    {column_strs}
    );
    """
    return await create_psql(create_text)
# async def ins_pizzeria(pizzeria_name):
#     df = await insert_psql(f"insert into pizzeria values (default ,'{pizzeria_name}', 5.0)")
#     return df